### ISSUE TITLE
An unexpected error occurred when run `yarn compile`

### ISSUE THREAD

**Issue by hadv** [paulrberg/solidity-template#59] opened 2021-08-19 05:18 UTC
An unexpected error occurred when run `yarn compile` as below output log due to hardhat compile the task before compile the smart contract?

```
An unexpected error occurred:

tasks/deployers/greeter.ts:4:43 - error TS2307: Cannot find module '../../typechain' or its corresponding type declarations.

4 import { Greeter, Greeter__factory } from "../../typechain";
```

**Comment by paulrberg** [comment] 2021-08-19 09:24
Yeah this is a known issue, it's a catch-22 caused by the fact that one of the Hardhat tasks imports the TypeChain bindings which are not generated yet. See https://github.com/ethereum-ts/TypeChain/issues/371.

It can be fixed by adding `TS_NODE_TRANSPILE_ONLY=true` before running the command, but that'd be a chore. That's why I added this flag in the `typechain` script in `package.json`; I should create a `compile` script and add the flag in there too.

**Comment by hadv** [comment] 2021-08-20 09:08
> It can be fixed by adding `TS_NODE_TRANSPILE_ONLY=true` before running the command, but that'd be a chore. That's why I added this flag in the `typechain` script in `package.json`; I should create a `compile` script and add the flag in there too.

Yeah, this way might be better

**Comment by paulrberg** [comment] 2021-09-03 21:34
Fixed in https://github.com/paulrberg/solidity-template/commit/015f05e168e9a418d0ec9b333dc54f6f99970086#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519.

**Closed by paulrberg** 2021-09-03 21:34 UTC
